# Generated by Django 6.0.1 on 2026-01-24 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='davlat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100)),
                ('poytaxti', models.CharField(max_length=100)),
                ('maydoni', models.FloatField()),
                ('aholi_soni', models.BigIntegerField()),
                ('tili', models.CharField(max_length=200)),
                ('pul_birligi', models.CharField(max_length=50)),
                ('qitasi', models.CharField(max_length=50)),
            ],
        ),
    ]
